### ISSUE TITLE
建议发新版本

### ISSUE THREAD

**Issue by yudeqang** [crawlab-team/crawlab-db#1]
go: finding module for package github.com/crawlab-team/crawlab-db/generic
github.com/crawlab-team/crawlab-core/controllers imports
	github.com/crawlab-team/crawlab-db/generic: module github.com/crawlab-team/crawlab-db@latest found (v0.1.3), but does not contain package github.com/crawlab-team/crawlab-db/generic

crawlab-core依赖会报错，现在还需要手动更新包

**Comment by doubletrey** [comment]
+1
